/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import static java.awt.AWTEventMulticaster.add;
import java.awt.FlowLayout;
import java.awt.Image;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Judy
 */
public class Menu extends javax.swing.JFrame {

    int[] ulam = new int[9];
    int[] kanin = new int[3];
    int[] inumin = new int[7];
    int[] panghimagas = new int[9];

    //Creates new form MENU
    public Menu() {
        initComponents();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    //declaring 
    DefaultTableModel dt;

    public void addTable(String name, int qty, double price) {

        dt = (DefaultTableModel) jTable1.getModel(); //getModel() Method returns information on the current data model during the processing of a personalized reverse engineering.

        DecimalFormat df = new DecimalFormat("00.00");
        String SubTotalPrice = df.format(price * qty);

        // ang ginagawa nito is para hindi madoble yung name na na-select sa menu
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            if (name == jTable1.getValueAt(row, 0)) {
                dt.removeRow(jTable1.convertRowIndexToModel(row));
            }
        }

        Vector v = new Vector();

        v.add(name);
        v.add(qty);
        v.add(SubTotalPrice);

        dt.addRow(v);

    }

    public void calculate() {
        //calculate total table values
        double total = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            total += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }

        DecimalFormat df = new DecimalFormat("00.00");
        jLabelTotal.setText(df.format(total)); //for TOTAL
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelForButtons = new javax.swing.JPanel();
        jButtonPanghimagas = new javax.swing.JButton();
        jButtonUlam = new javax.swing.JButton();
        jButtonKanin = new javax.swing.JButton();
        jButtonInumin = new javax.swing.JButton();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        adobo = new javax.swing.JButton();
        sinigang = new javax.swing.JButton();
        karekare = new javax.swing.JButton();
        nilaga = new javax.swing.JButton();
        sisig = new javax.swing.JButton();
        tinola = new javax.swing.JButton();
        pinakbet = new javax.swing.JButton();
        kaldereta = new javax.swing.JButton();
        bistek = new javax.swing.JButton();
        alabel1 = new java.awt.Label();
        alabel2 = new java.awt.Label();
        alabel3 = new java.awt.Label();
        alabel4 = new java.awt.Label();
        alabel5 = new java.awt.Label();
        alabel6 = new java.awt.Label();
        alabel7 = new java.awt.Label();
        alabel8 = new java.awt.Label();
        alabel9 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        maliit = new javax.swing.JButton();
        malaki = new javax.swing.JButton();
        sinangag = new javax.swing.JButton();
        alabel10 = new java.awt.Label();
        alabel11 = new java.awt.Label();
        alabel12 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cocacola = new javax.swing.JButton();
        royal = new javax.swing.JButton();
        sprite = new javax.swing.JButton();
        mountainDew = new javax.swing.JButton();
        sevenUp = new javax.swing.JButton();
        rc = new javax.swing.JButton();
        pepsi = new javax.swing.JButton();
        alabel13 = new java.awt.Label();
        alabel14 = new java.awt.Label();
        alabel15 = new java.awt.Label();
        alabel16 = new java.awt.Label();
        alabel17 = new java.awt.Label();
        alabel18 = new java.awt.Label();
        alabel19 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        halohalo = new javax.swing.JButton();
        puto = new javax.swing.JButton();
        lecheFlan = new javax.swing.JButton();
        ginataangBiloBilo = new javax.swing.JButton();
        kutsinta = new javax.swing.JButton();
        eggPie = new javax.swing.JButton();
        bukoPandan = new javax.swing.JButton();
        biko = new javax.swing.JButton();
        turon = new javax.swing.JButton();
        alabel20 = new java.awt.Label();
        alabel21 = new java.awt.Label();
        alabel22 = new java.awt.Label();
        alabel23 = new java.awt.Label();
        alabel24 = new java.awt.Label();
        alabel25 = new java.awt.Label();
        alabel26 = new java.awt.Label();
        alabel27 = new java.awt.Label();
        alabel28 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonReset = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonPay = new javax.swing.JButton();
        jLabelT = new javax.swing.JLabel();
        totalTitle2 = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelCash = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldPay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelForButtons.setBackground(new java.awt.Color(51, 51, 51));
        PanelForButtons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelForButtons.setForeground(new java.awt.Color(255, 255, 255));
        PanelForButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPanghimagas.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPanghimagas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPanghimagas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPanghimagas.setText("PANGHIMAGAS");
        jButtonPanghimagas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPanghimagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanghimagasActionPerformed(evt);
            }
        });
        PanelForButtons.add(jButtonPanghimagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 130, 75));

        jButtonUlam.setBackground(new java.awt.Color(153, 153, 153));
        jButtonUlam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUlam.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUlam.setText("ULAM");
        jButtonUlam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUlam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlamActionPerformed(evt);
            }
        });
        PanelForButtons.add(jButtonUlam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 75));

        jButtonKanin.setBackground(new java.awt.Color(153, 153, 153));
        jButtonKanin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonKanin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKanin.setText("KANIN");
        jButtonKanin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonKanin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKaninActionPerformed(evt);
            }
        });
        PanelForButtons.add(jButtonKanin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 75));

        jButtonInumin.setBackground(new java.awt.Color(153, 153, 153));
        jButtonInumin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonInumin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInumin.setText("INUMIN");
        jButtonInumin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInumin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInuminActionPerformed(evt);
            }
        });
        PanelForButtons.add(jButtonInumin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 130, 75));

        getContentPane().add(PanelForButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 760));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adobo.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\adobo.jpg")); // NOI18N
        adobo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adoboMouseClicked(evt);
            }
        });
        adobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoboActionPerformed(evt);
            }
        });
        jPanel1.add(adobo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, 110));

        sinigang.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\sinigang.jpg")); // NOI18N
        sinigang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinigangActionPerformed(evt);
            }
        });
        jPanel1.add(sinigang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, 110));

        karekare.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\kare-kare.jpg")); // NOI18N
        karekare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karekareActionPerformed(evt);
            }
        });
        jPanel1.add(karekare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 110, 110));

        nilaga.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\nilaga.jpg")); // NOI18N
        nilaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilagaActionPerformed(evt);
            }
        });
        jPanel1.add(nilaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 110, 110));

        sisig.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\sigsig.jpg")); // NOI18N
        sisig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisigActionPerformed(evt);
            }
        });
        jPanel1.add(sisig, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 110, 110));

        tinola.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\tinola.jpg")); // NOI18N
        tinola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinolaActionPerformed(evt);
            }
        });
        jPanel1.add(tinola, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, 110));

        pinakbet.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\pinakbet.jpg")); // NOI18N
        pinakbet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinakbetActionPerformed(evt);
            }
        });
        jPanel1.add(pinakbet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 110, 110));

        kaldereta.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\kaldereta.jpg")); // NOI18N
        kaldereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalderetaActionPerformed(evt);
            }
        });
        jPanel1.add(kaldereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 110, 110));

        bistek.setIcon(new javax.swing.ImageIcon("C:\\MGA ULAM\\bistek.jpg")); // NOI18N
        bistek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bistekActionPerformed(evt);
            }
        });
        jPanel1.add(bistek, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, 110));

        alabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel1.setForeground(new java.awt.Color(255, 255, 255));
        alabel1.setText("ADOBO");
        jPanel1.add(alabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, 20));

        alabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel2.setForeground(new java.awt.Color(255, 255, 255));
        alabel2.setText("SINIGANG");
        jPanel1.add(alabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, 20));

        alabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel3.setForeground(new java.awt.Color(255, 255, 255));
        alabel3.setText("KARE-KARE");
        jPanel1.add(alabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, 20));

        alabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel4.setForeground(new java.awt.Color(255, 255, 255));
        alabel4.setText("NILAGA");
        jPanel1.add(alabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 60, 20));

        alabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel5.setForeground(new java.awt.Color(255, 255, 255));
        alabel5.setText("SISIG");
        jPanel1.add(alabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 50, 20));

        alabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel6.setForeground(new java.awt.Color(255, 255, 255));
        alabel6.setText("TINOLA");
        jPanel1.add(alabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 60, 20));

        alabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel7.setForeground(new java.awt.Color(255, 255, 255));
        alabel7.setText("PINAKBET");
        jPanel1.add(alabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 80, 20));

        alabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel8.setForeground(new java.awt.Color(255, 255, 255));
        alabel8.setText("KALDERETA");
        jPanel1.add(alabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 90, 20));

        alabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel9.setForeground(new java.awt.Color(255, 255, 255));
        alabel9.setText("BISTEK");
        jPanel1.add(alabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 60, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NANAY'S CANTEEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 350, 50));

        jTabbedPaneMenu.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maliit.setIcon(new javax.swing.ImageIcon("C:\\MGA KANIN\\maliit na sukat ng tasa.jpg")); // NOI18N
        maliit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maliitMouseClicked(evt);
            }
        });
        maliit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maliitActionPerformed(evt);
            }
        });
        jPanel2.add(maliit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 110));

        malaki.setIcon(new javax.swing.ImageIcon("C:\\MGA KANIN\\malaking sukat ng tasa.jpg")); // NOI18N
        malaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malakiMouseClicked(evt);
            }
        });
        malaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malakiActionPerformed(evt);
            }
        });
        jPanel2.add(malaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 110, 110));

        sinangag.setIcon(new javax.swing.ImageIcon("C:\\MGA KANIN\\sinangag.jpg")); // NOI18N
        sinangag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinangagMouseClicked(evt);
            }
        });
        sinangag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinangagActionPerformed(evt);
            }
        });
        jPanel2.add(sinangag, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 110, 110));

        alabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel10.setForeground(new java.awt.Color(255, 255, 255));
        alabel10.setText("SINANGAG");
        jPanel2.add(alabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, 20));

        alabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel11.setForeground(new java.awt.Color(255, 255, 255));
        alabel11.setText("MALAKING SUKAT");
        jPanel2.add(alabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, 20));

        alabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel12.setForeground(new java.awt.Color(255, 255, 255));
        alabel12.setText("MALIIT NA SUKAT");
        jPanel2.add(alabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));
        alabel12.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NANAY'S CANTEEN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 40, -1, 50));

        jTabbedPaneMenu.addTab("tab2", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("SMALL CUP SIZE");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cocacola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cocacola.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\coca-cola.jpg")); // NOI18N
        cocacola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cocacolaMouseClicked(evt);
            }
        });
        cocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocacolaActionPerformed(evt);
            }
        });
        jPanel3.add(cocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 110));

        royal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        royal.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\royal.jpg")); // NOI18N
        royal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                royalMouseClicked(evt);
            }
        });
        royal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                royalActionPerformed(evt);
            }
        });
        jPanel3.add(royal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 110));

        sprite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sprite.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\sprite.jpg")); // NOI18N
        sprite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spriteMouseClicked(evt);
            }
        });
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });
        jPanel3.add(sprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 110));

        mountainDew.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\mountain-dew.jpg")); // NOI18N
        mountainDew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mountainDewMouseClicked(evt);
            }
        });
        mountainDew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountainDewActionPerformed(evt);
            }
        });
        jPanel3.add(mountainDew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, 110));

        sevenUp.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\7-up.jpg")); // NOI18N
        sevenUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenUpMouseClicked(evt);
            }
        });
        sevenUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenUpActionPerformed(evt);
            }
        });
        jPanel3.add(sevenUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, 110));

        rc.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\rc.jpg")); // NOI18N
        rc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rcMouseClicked(evt);
            }
        });
        rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcActionPerformed(evt);
            }
        });
        jPanel3.add(rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 110, 110));

        pepsi.setIcon(new javax.swing.ImageIcon("C:\\MGA INUMIN\\pepsi.jpg")); // NOI18N
        pepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pepsiMouseClicked(evt);
            }
        });
        pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiActionPerformed(evt);
            }
        });
        jPanel3.add(pepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 110, 110));

        alabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel13.setForeground(new java.awt.Color(255, 255, 255));
        alabel13.setText("COCA-COLA");
        jPanel3.add(alabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        alabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel14.setForeground(new java.awt.Color(255, 255, 255));
        alabel14.setText("ROYAL");
        jPanel3.add(alabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 20));

        alabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel15.setForeground(new java.awt.Color(255, 255, 255));
        alabel15.setText("SPRITE");
        jPanel3.add(alabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, 20));

        alabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel16.setForeground(new java.awt.Color(255, 255, 255));
        alabel16.setText("MOUNTAIN DEW");
        jPanel3.add(alabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        alabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel17.setForeground(new java.awt.Color(255, 255, 255));
        alabel17.setText("7-UP");
        jPanel3.add(alabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, 20));

        alabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel18.setForeground(new java.awt.Color(255, 255, 255));
        alabel18.setText("RC");
        jPanel3.add(alabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, 20));

        alabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel19.setForeground(new java.awt.Color(255, 255, 255));
        alabel19.setText("PEPSI");
        jPanel3.add(alabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NANAY'S CANTEEN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 40, -1, 50));

        jTabbedPaneMenu.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        halohalo.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\halo-halo.jpg")); // NOI18N
        halohalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                halohaloMouseClicked(evt);
            }
        });
        halohalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halohaloActionPerformed(evt);
            }
        });
        jPanel4.add(halohalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, 110));

        puto.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\puto.jpg")); // NOI18N
        puto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                putoMouseClicked(evt);
            }
        });
        puto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putoActionPerformed(evt);
            }
        });
        jPanel4.add(puto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, 110));

        lecheFlan.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\leche flan.jpg")); // NOI18N
        lecheFlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecheFlanMouseClicked(evt);
            }
        });
        lecheFlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecheFlanActionPerformed(evt);
            }
        });
        jPanel4.add(lecheFlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, 110));

        ginataangBiloBilo.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\ginataang bilobilo.jpg")); // NOI18N
        ginataangBiloBilo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ginataangBiloBiloMouseClicked(evt);
            }
        });
        ginataangBiloBilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ginataangBiloBiloActionPerformed(evt);
            }
        });
        jPanel4.add(ginataangBiloBilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 110));

        kutsinta.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\kutsinta.jpg")); // NOI18N
        kutsinta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kutsintaMouseClicked(evt);
            }
        });
        kutsinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutsintaActionPerformed(evt);
            }
        });
        jPanel4.add(kutsinta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 110));

        eggPie.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\egg pie.jpg")); // NOI18N
        eggPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eggPieMouseClicked(evt);
            }
        });
        eggPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggPieActionPerformed(evt);
            }
        });
        jPanel4.add(eggPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 110));

        bukoPandan.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\buko pandan.jpg")); // NOI18N
        bukoPandan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukoPandanMouseClicked(evt);
            }
        });
        bukoPandan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukoPandanActionPerformed(evt);
            }
        });
        jPanel4.add(bukoPandan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 110, 110));

        biko.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\biko.jpg")); // NOI18N
        biko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bikoMouseClicked(evt);
            }
        });
        biko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikoActionPerformed(evt);
            }
        });
        jPanel4.add(biko, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 110, 110));

        turon.setIcon(new javax.swing.ImageIcon("C:\\MGA PANGHIMAGAS\\turon.jpg")); // NOI18N
        turon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turonMouseClicked(evt);
            }
        });
        turon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turonActionPerformed(evt);
            }
        });
        jPanel4.add(turon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 110, 110));

        alabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel20.setForeground(new java.awt.Color(255, 255, 255));
        alabel20.setText("HALO-HALO");
        jPanel4.add(alabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 20));

        alabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel21.setForeground(new java.awt.Color(255, 255, 255));
        alabel21.setText("PUTO");
        jPanel4.add(alabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 20));

        alabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel22.setForeground(new java.awt.Color(255, 255, 255));
        alabel22.setText("LECHE FLAN");
        jPanel4.add(alabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 20));

        alabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        alabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel23.setForeground(new java.awt.Color(255, 255, 255));
        alabel23.setText("GINATAANG BILO-BILO");
        jPanel4.add(alabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        alabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel24.setForeground(new java.awt.Color(255, 255, 255));
        alabel24.setText("KUTSINTA");
        jPanel4.add(alabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, 20));

        alabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel25.setForeground(new java.awt.Color(255, 255, 255));
        alabel25.setText("EGG PIE");
        jPanel4.add(alabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, 20));

        alabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel26.setForeground(new java.awt.Color(255, 255, 255));
        alabel26.setText("BUKO PANDAN");
        jPanel4.add(alabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, 20));

        alabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel27.setForeground(new java.awt.Color(255, 255, 255));
        alabel27.setText("BIKO");
        jPanel4.add(alabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, 20));

        alabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alabel28.setForeground(new java.awt.Color(255, 255, 255));
        alabel28.setText("TURON");
        jPanel4.add(alabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NANAY'S CANTEEN");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 50));

        jTabbedPaneMenu.addTab("tab4", jPanel4);

        getContentPane().add(jTabbedPaneMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -40, 510, 800));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 570));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 350, 590));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jButtonReset.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("RESET");
        jButtonReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonPrint.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrint.setText("PRINT");
        jButtonPrint.setToolTipText("");
        jButtonPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonRemove.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemove.setText("REMOVE");
        jButtonRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonPay.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPay.setText("PAY");
        jButtonPay.setToolTipText("");
        jButtonPay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });

        jLabelT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelT.setText("TOTAL :");

        totalTitle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalTitle2.setForeground(new java.awt.Color(255, 255, 255));
        totalTitle2.setText("CASH : ");

        jLabelC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC.setText("CHANGE:");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setText("00");

        jLabelChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChange.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChange.setText("00");

        jButtonExit.setBackground(new java.awt.Color(153, 153, 153));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("EXIT");
        jButtonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCash.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCash.setText("00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTitle2)
                    .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 670, 170));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jTextFieldPay.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jTextFieldPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPayActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnClear.setText("CLR");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextFieldPay, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextFieldPay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 320, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        //remove item
        try {

            int selectedRow = jTable1.getSelectedRow();
            String removedItem = jTable1.getValueAt(selectedRow, 0).toString();
            switch (removedItem) {
                case "ADOBO              ":
                    ulam[0] = 0;
                    break;
                case "SINIGANG           ":
                    ulam[1] = 0;
                    break;
                case "PINAKBET           ":
                    ulam[2] = 0;
                    break;
                case "BISTEK             ":
                    ulam[3] = 0;
                    break;
                case "SISIG\t":
                    ulam[4] = 0;
                    break;
                case "TINOLA             ":
                    ulam[5] = 0;
                    break;
                case "KARE-KARE          ":
                    ulam[6] = 0;
                    break;
                case "KALDERETA          ":
                    ulam[7] = 0;
                    break;
                case "NILAGA             ":
                    ulam[8] = 0;
                    break;
                case "MALIIT NA SUKAT    ":
                    kanin[0] = 0;
                    break;
                case "SINANGAG           ":
                    kanin[2] = 0;
                    break;
                case "MALAKING SUKAT     ":
                    kanin[1] = 0;
                    break;
                case "COCA-COLA          ":
                    inumin[0] = 0;
                    break;
                case "ROYAL              ":
                    inumin[1] = 0;
                    break;
                case "SPRITE             ":
                    inumin[2] = 0;
                    break;
                case "MOUNTAIN DEW       ":
                    inumin[3] = 0;
                    break;
                case "7-UP\t":
                    inumin[4] = 0;
                    break;
                case "RC\t":
                    inumin[5] = 0;
                    break;
                case "PEPSI\t":
                    inumin[6] = 0;
                    break;
                case "HALO-HALO      ":
                    panghimagas[0] = 0;
                    break;
                case "PUTO           ":
                    panghimagas[1] = 0;
                    break;
                case "LECHE FLAN     ":
                    panghimagas[2] = 0;
                    break;
                case "GINATAANG BILO-BILO":
                    panghimagas[3] = 0;
                    break;
                case "KUTSINTA           ":
                    panghimagas[4] = 0;
                    break;
                case "EGG PIE            ":
                    panghimagas[5] = 0;
                    break;
                case "BUKO PANDAN        ":
                    panghimagas[6] = 0;
                    break;
                case "BIKO               ":
                    panghimagas[7] = 0;
                    break;
                case "TURON              ":
                    panghimagas[8] = 0;
            }
            dt = (DefaultTableModel) jTable1.getModel();
            dt.removeRow(jTable1.getSelectedRow());
            calculate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Select an item to remove!", "POS SYSTEM", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonPanghimagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanghimagasActionPerformed
        jTabbedPaneMenu.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonPanghimagasActionPerformed

    private void adoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoboActionPerformed
        // btn code
        ulam[0]++;
        addTable("ADOBO              ", ulam[0], 30.00);
        calculate();
    }//GEN-LAST:event_adoboActionPerformed

    private void adoboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adoboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adoboMouseClicked

    private void maliitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maliitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maliitMouseClicked

    private void maliitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maliitActionPerformed
        // btn code
        kanin[0]++;
        addTable("MALIIT NA SUKAT    ", kanin[0], 10.00);
        calculate();
    }//GEN-LAST:event_maliitActionPerformed

    private void sinangagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinangagMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sinangagMouseClicked

    private void sinangagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinangagActionPerformed
        // btn code
        kanin[2]++;
        addTable("SINANGAG           ", kanin[2], 20.00);
        calculate();
    }//GEN-LAST:event_sinangagActionPerformed

    private void malakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malakiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_malakiMouseClicked

    private void malakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malakiActionPerformed
        // btn code
        kanin[1]++;
        addTable("MALAKING SUKAT     ", kanin[1], 15.00);
        calculate();
    }//GEN-LAST:event_malakiActionPerformed

    private void cocacolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cocacolaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cocacolaMouseClicked

    private void cocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocacolaActionPerformed
        // btn code
        inumin[0]++;
        addTable("COCA-COLA          ", inumin[0], 25.00);
        calculate();
    }//GEN-LAST:event_cocacolaActionPerformed

    private void royalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_royalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_royalMouseClicked

    private void royalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_royalActionPerformed
        // btn code
        inumin[1]++;
        addTable("ROYAL              ", inumin[1], 25.00);
        calculate();
    }//GEN-LAST:event_royalActionPerformed

    private void spriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spriteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteMouseClicked

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        // btn code
        inumin[2]++;
        addTable("SPRITE             ", inumin[2], 25.00);
        calculate();
    }//GEN-LAST:event_spriteActionPerformed

    private void mountainDewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mountainDewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mountainDewMouseClicked

    private void mountainDewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountainDewActionPerformed
        // btn code
        inumin[3]++;
        addTable("MOUNTAIN DEW       ", inumin[3], 20.00);
        calculate();
    }//GEN-LAST:event_mountainDewActionPerformed

    private void sevenUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenUpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenUpMouseClicked

    private void sevenUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenUpActionPerformed
        // btn code
        inumin[4]++;
        addTable("7-UP\t", inumin[4], 20.00);
        calculate();
    }//GEN-LAST:event_sevenUpActionPerformed

    private void rcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rcMouseClicked

    private void rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcActionPerformed
        // btn code
        inumin[5]++;
        addTable("RC\t", inumin[5], 20.00);
        calculate();
    }//GEN-LAST:event_rcActionPerformed

    private void pepsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pepsiMouseClicked

    private void pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiActionPerformed
        // btn code
        inumin[6]++;
        addTable("PEPSI\t", inumin[6], 15.00);
        calculate();
    }//GEN-LAST:event_pepsiActionPerformed

    private void ginataangBiloBiloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ginataangBiloBiloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ginataangBiloBiloMouseClicked

    private void ginataangBiloBiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ginataangBiloBiloActionPerformed
        // btn code
        panghimagas[3]++;
        addTable("GINATAANG BILO-BILO", panghimagas[3], 15.00);
        calculate();
    }//GEN-LAST:event_ginataangBiloBiloActionPerformed

    private void halohaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_halohaloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_halohaloMouseClicked

    private void halohaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halohaloActionPerformed
        // btn code
        panghimagas[0]++;
        addTable("HALO-HALO      ", panghimagas[0], 25.00);
        calculate();
    }//GEN-LAST:event_halohaloActionPerformed

    private void putoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_putoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_putoMouseClicked

    private void putoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putoActionPerformed
        // btn code
        panghimagas[1]++;
        addTable("PUTO           ", panghimagas[1], 15.00);
        calculate();
    }//GEN-LAST:event_putoActionPerformed

    private void bukoPandanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukoPandanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bukoPandanMouseClicked

    private void bukoPandanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukoPandanActionPerformed
        // btn code
        panghimagas[6]++;
        addTable("BUKO PANDAN        ", panghimagas[6], 15.00);
        calculate();
    }//GEN-LAST:event_bukoPandanActionPerformed

    private void bikoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bikoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bikoMouseClicked

    private void bikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikoActionPerformed
        // btn code
        panghimagas[7]++;
        addTable("BIKO               ", panghimagas[7], 15.00);
        calculate();
    }//GEN-LAST:event_bikoActionPerformed

    private void turonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_turonMouseClicked

    private void turonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turonActionPerformed
        // btn code
        panghimagas[8]++;
        addTable("TURON              ", panghimagas[8], 15.00);
        calculate();
    }//GEN-LAST:event_turonActionPerformed

    private void kutsintaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kutsintaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kutsintaMouseClicked

    private void kutsintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutsintaActionPerformed
        // btn code
        panghimagas[4]++;
        addTable("KUTSINTA           ", panghimagas[4], 15.00);
        calculate();
    }//GEN-LAST:event_kutsintaActionPerformed

    private void eggPieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eggPieMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eggPieMouseClicked

    private void eggPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggPieActionPerformed
        // btn code
        panghimagas[5]++;
        addTable("EGG PIE            ", panghimagas[5], 20.00);
        calculate();
    }//GEN-LAST:event_eggPieActionPerformed

    private void lecheFlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecheFlanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lecheFlanMouseClicked

    private void lecheFlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecheFlanActionPerformed
        // btn code
        panghimagas[2]++;
        addTable("LECHE FLAN     ", panghimagas[2], 30.00);
        calculate();
    }//GEN-LAST:event_lecheFlanActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed

        //remove rows for the bottom one by one
        for (int i = dt.getRowCount() - 1; i >= 0; i--) {
            dt.removeRow(i);
        }
        calculate();

        for (int i = 0; i < ulam.length; i++) {
            ulam[i] = 0;
        }
        for (int i = 0; i < kanin.length; i++) {
            kanin[i] = 0;
        }
        for (int i = 0; i < inumin.length; i++) {
            inumin[i] = 0;
        }
        for (int i = 0; i < panghimagas.length; i++) {
            panghimagas[i] = 0;
        }

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        //bill print
        BillPrint billP = new BillPrint();
        try {

            billP.bill.setText("\t   NANAY'S CANTEEN \n");
            billP.bill.setText(billP.bill.getText() + "\t   McArthur Hwy, Nancayasan, \n");
            billP.bill.setText(billP.bill.getText() + "\t   Urdaneta, Pangasinan \n");
            billP.bill.setText(billP.bill.getText() + "\t   (075) 653 7240 \n");
            billP.bill.setText(billP.bill.getText() + " --------------------------------------------------------------------------------- \n");
            billP.bill.setText(billP.bill.getText() + "     Item                   \tQty \tPrice \n");
            billP.bill.setText(billP.bill.getText() + " --------------------------------------------------------------------------------- \n");

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();

            //get table product details
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String Name = df.getValueAt(i, 0).toString();
                String Qty = df.getValueAt(i, 1).toString();
                String Price = df.getValueAt(i, 2).toString();

                billP.bill.setText(billP.bill.getText() + "     " + Name + "\t" + Qty + "\t" + Price + "\n");
            }

            billP.bill.setText(billP.bill.getText() + " ---------------------------------------------------------------------------------- \n");
            billP.bill.setText(billP.bill.getText() + " Total: " + jLabelTotal.getText() + "\n");
            billP.bill.setText(billP.bill.getText() + " Cash: " + jTextFieldPay.getText() + "\n");
            billP.bill.setText(billP.bill.getText() + " Change: " + jLabelChange.getText() + "\n");
            billP.bill.setText(billP.bill.getText() + " ---------------------------------------------------------------------------------- \n");
            billP.bill.setText(billP.bill.getText() + " \tThank You! Come Again!!!\n");
            billP.bill.setText(billP.bill.getText() + " ---------------------------------------------------------------------------------- \n");
           
            billP.setVisible(true);
            //dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonUlamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlamActionPerformed
        jTabbedPaneMenu.setSelectedIndex(0); //ang magpapakitang jpanel/menu is yung adobo
    }//GEN-LAST:event_jButtonUlamActionPerformed

    private void jButtonKaninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKaninActionPerformed
        jTabbedPaneMenu.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonKaninActionPerformed

    private void jButtonInuminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInuminActionPerformed
        jTabbedPaneMenu.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonInuminActionPerformed

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed

        // pay button
        double total = Double.parseDouble(jLabelTotal.getText());
        double pay = Double.parseDouble(jTextFieldPay.getText());
        double balance = pay - total;

        DecimalFormat df = new DecimalFormat("00.00");
        jLabelChange.setText(df.format(balance));

        jLabelCash.setText(jTextFieldPay.getText());

    }//GEN-LAST:event_jButtonPayActionPerformed

    private void sinigangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinigangActionPerformed
        // btn code
        ulam[1]++;
        addTable("SINIGANG           ", ulam[1], 30.00);
        calculate();
    }//GEN-LAST:event_sinigangActionPerformed

    private void karekareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karekareActionPerformed
        // btn code
        ulam[6]++;
        addTable("KARE-KARE          ", ulam[6], 50.00);
        calculate();
    }//GEN-LAST:event_karekareActionPerformed

    private void nilagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilagaActionPerformed
        // btn code
        ulam[8]++;
        addTable("NILAGA             ", ulam[8], 50.00);
        calculate();
    }//GEN-LAST:event_nilagaActionPerformed

    private void sisigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisigActionPerformed
        // btn code
        ulam[4]++;
        addTable("SISIG\t", ulam[4], 40.00);
        calculate();
    }//GEN-LAST:event_sisigActionPerformed

    private void tinolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinolaActionPerformed
        // btn code
        ulam[5]++;
        addTable("TINOLA             ", ulam[5], 40.00);
        calculate();
    }//GEN-LAST:event_tinolaActionPerformed

    private void pinakbetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinakbetActionPerformed
        // btn code
        ulam[2]++;
        addTable("PINAKBET           ", ulam[2], 30.00);
        calculate();
    }//GEN-LAST:event_pinakbetActionPerformed

    private void kalderetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalderetaActionPerformed
        // btn code
        ulam[7]++;
        addTable("KALDERETA          ", ulam[7], 50.00);
        calculate();
    }//GEN-LAST:event_kalderetaActionPerformed

    private void bistekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bistekActionPerformed
        // btn code
        ulam[3]++;
        addTable("BISTEK             ", ulam[3], 40.00);
        calculate();
    }//GEN-LAST:event_bistekActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
      
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "POS SYSTEM", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            dispose();
        }

    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPayActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn7.getText());

            jLabelCash.setText(jbtn7.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn7.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }

    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn8.getText());
            jLabelCash.setText(jbtn8.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn8.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn9.getText());
            jLabelCash.setText(jbtn9.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn9.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn4.getText());
            jLabelCash.setText(jbtn4.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn4.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn5.getText());
            jLabelCash.setText(jbtn5.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn5.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn6.getText());
            jLabelCash.setText(jbtn6.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn6.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn1.getText());
            jLabelCash.setText(jbtn1.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn1.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn2.getText());
            jLabelCash.setText(jbtn2.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn2.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn3.getText());
            jLabelCash.setText(jbtn3.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn3.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String EnterNumber = jTextFieldPay.getText();

        if (EnterNumber == "") {
            jTextFieldPay.setText(jbtn0.getText());
            jLabelCash.setText(jbtn0.getText());
        } else {
            EnterNumber = jTextFieldPay.getText() + jbtn0.getText();
            jTextFieldPay.setText(EnterNumber);
            jLabelCash.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if (!jTextFieldPay.getText().contains(".")) {
            jTextFieldPay.setText(jTextFieldPay.getText() + jbtnDot.getText());
            jLabelCash.setText(jLabelCash.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jTextFieldPay.setText("");
        jLabelChange.setText("00");
        jLabelCash.setText("00");
    }//GEN-LAST:event_jbtnClearActionPerformed

    public static void main(String args[]) {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelForButtons;
    private javax.swing.JButton adobo;
    private java.awt.Label alabel1;
    private java.awt.Label alabel10;
    private java.awt.Label alabel11;
    private java.awt.Label alabel12;
    private java.awt.Label alabel13;
    private java.awt.Label alabel14;
    private java.awt.Label alabel15;
    private java.awt.Label alabel16;
    private java.awt.Label alabel17;
    private java.awt.Label alabel18;
    private java.awt.Label alabel19;
    private java.awt.Label alabel2;
    private java.awt.Label alabel20;
    private java.awt.Label alabel21;
    private java.awt.Label alabel22;
    private java.awt.Label alabel23;
    private java.awt.Label alabel24;
    private java.awt.Label alabel25;
    private java.awt.Label alabel26;
    private java.awt.Label alabel27;
    private java.awt.Label alabel28;
    private java.awt.Label alabel3;
    private java.awt.Label alabel4;
    private java.awt.Label alabel5;
    private java.awt.Label alabel6;
    private java.awt.Label alabel7;
    private java.awt.Label alabel8;
    private java.awt.Label alabel9;
    private javax.swing.JButton biko;
    private javax.swing.JButton bistek;
    private javax.swing.JButton bukoPandan;
    private javax.swing.JButton cocacola;
    private javax.swing.JButton eggPie;
    private javax.swing.JButton ginataangBiloBilo;
    private javax.swing.JButton halohalo;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonInumin;
    private javax.swing.JButton jButtonKanin;
    private javax.swing.JButton jButtonPanghimagas;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUlam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelCash;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    protected javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPay;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton kaldereta;
    private javax.swing.JButton karekare;
    private javax.swing.JButton kutsinta;
    private javax.swing.JButton lecheFlan;
    private javax.swing.JButton malaki;
    private javax.swing.JButton maliit;
    private javax.swing.JButton mountainDew;
    private javax.swing.JButton nilaga;
    private javax.swing.JButton pepsi;
    private javax.swing.JButton pinakbet;
    private javax.swing.JButton puto;
    private javax.swing.JButton rc;
    private javax.swing.JButton royal;
    private javax.swing.JButton sevenUp;
    private javax.swing.JButton sinangag;
    private javax.swing.JButton sinigang;
    private javax.swing.JButton sisig;
    private javax.swing.JButton sprite;
    private javax.swing.JButton tinola;
    private javax.swing.JLabel totalTitle2;
    private javax.swing.JButton turon;
    // End of variables declaration//GEN-END:variables

}
